// This is an autogenerated file from Firebase Studio.
'use client';
import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { ThemeProvider } from '@/components/theme-provider';
import { FloatingButtons } from '@/components/layout/FloatingButtons';
import { Sidebar } from '@/components/layout/Sidebar';
import TestimonialsSidebar from '@/components/sidebar/TestimonialsSidebar';
import HistorySidebar from '@/components/sidebar/HistorySidebar';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

// export const metadata: Metadata = {
//   title: 'Skill Up Career AI',
//   description: 'A career navigator platform for students and professionals.',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarContent, setSidebarContent] = useState<React.ReactNode | null>(null);

  const handleShowTestimonials = () => {
    setSidebarContent(<TestimonialsSidebar />);
  };

  const handleShowHistory = () => {
    setSidebarContent(<HistorySidebar />);
  };
  
  return (
    <html lang="en" suppressHydrationWarning>
       <head>
        <title>Skill Up Career AI</title>
        <meta name="description" content="A career navigator platform for students and professionals." />
      </head>
      <body className={`${inter.variable} font-sans antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative flex flex-col min-h-screen">
            <Header onShowTestimonials={handleShowTestimonials} onShowHistory={handleShowHistory}/>
            <main className="flex-grow">{children}</main>
            <Footer />
          </div>
          <FloatingButtons />
          <Sidebar isOpen={!!sidebarContent} onClose={() => setSidebarContent(null)}>
            {sidebarContent}
          </Sidebar>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
